export const CONTRACT_SCHEMA_VERSION = 1;

export const CONTRACT_KINDS = {
  API: 'api',
  RPC: 'rpc',
};

export const CONTRACT_PROTOCOLS = {
  HTTP_JSON: 'http-json',
  RPC_JSON: 'rpc-json',
};

export const CONTRACT_ROLES = {
  PRODUCER: 'producer',
  CONSUMER: 'consumer',
  REVIEWER: 'reviewer',
};

export const CONTRACT_LIFECYCLE_STATUSES = {
  DRAFT: 'draft',
  ACTIVE: 'active',
  DEPRECATED: 'deprecated',
};

export const CONTRACT_COMPATIBILITY = {
  BACKWARD_COMPATIBLE: 'backward-compatible',
  BREAKING: 'breaking',
  INTERNAL_ONLY: 'internal-only',
};

export const CONTRACT_CHECK_CODES = {
  INVALID_FILE_NAME: 'INVALID_FILE_NAME',
  INVALID_JSON: 'INVALID_JSON',
  INVALID_CONTRACT_ID: 'INVALID_CONTRACT_ID',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_KIND: 'INVALID_KIND',
  INVALID_PROTOCOL: 'INVALID_PROTOCOL',
  DUPLICATE_CONTRACT_ID: 'DUPLICATE_CONTRACT_ID',
  MISSING_HTTP_ENDPOINT: 'MISSING_HTTP_ENDPOINT',
  MISSING_RPC_TARGET: 'MISSING_RPC_TARGET',
  MISSING_BOUND_CONTRACT: 'MISSING_BOUND_CONTRACT',
  OPEN_CONTRACT_QUESTIONS: 'OPEN_CONTRACT_QUESTIONS',
  BOUND_FILE_MISSING: 'BOUND_FILE_MISSING',
};
